### ISSUE TITLE
Item's "Status" updated using before_save needs extra checks

### ISSUE THREAD

**Issue by jlm** [jlm/maint#65] opened 2020-09-23 16:14 UTC
There's an inconsistency in different pieces of code handling the minutes of an item.  The database can contain invalid minute entries, having NULL dates.  It's not clear whether this is as a result of failing to destroy them when their owning item is destroyed, or just for historical reasons.
The "Status" update in the item controller needs to disregard minutes having NULL dates.

**Comment by PaulCongdon** [comment] 2020-09-23 16:38
I believe the issue could be resolved in the items model by ignoring
minutes that do not have a date.  I believe the issue is with the
before_save method below;  Ordering the minutes by date when the date does
not exist is potentially an issue.

class Item < ActiveRecord::Base
  has_many :minutes
  has_many :meetings, through: :minutes
  belongs_to :minst
  has_one :request
# :number, :date, :standard, :clause, :subject, :draft
  validates :number, presence: true, format: { with: /\A\d{4}\z/, message:
"must be 4 decimal digits" }
  validates :date, presence: true
  validates :standard, presence: true, length: { in: 3..50 }
  validates :subject, presence: true, length: { maximum: 200 }, unless:
"Rails.application.config.importing"

  before_save {
    lastminst = self.minutes.order(:date, :id).last.minst unless
self.minutes.blank?
    self.minst = lastminst unless lastminst.nil?
  }

  CLOSED_CODES = ["P", "J", "W"]
  scope :closed, ->   { joins(:minst).where("minsts.code IN (?)",
CLOSED_CODES) }
  scope :open,   ->   { joins(:minst).where.not("minsts.code IN (?)",
CLOSED_CODES)  }
  scope :review, ->   { joins(:minst).where.not("minsts.code IN (?)",
CLOSED_CODES + ["V"])  }

  def is_closed?
    self.minst && (CLOSED_CODES.include? self.minst.code)
  end
end

**Closed** 2023-10-18 19:12 UTC
Labels: bug
